server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles.active: ${ACTIVE_PROFILE}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka