server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${APPLICATION_NAME}
  profiles.active: ${ACTIVE_PROFILE}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user-api/**
          filters:
            - RewritePath=/user-api/(?<path>.*), /$\{path}
        - id: account-management
          uri: lb://account-management
          predicates:
              - Path=/account-management/**
          filters:
              - RewritePath=/account-management/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
#    fetchRegistry: true
#    registerWithEureka: true
#  instance:
#    preferIpAddress: true
